iam_roles_to_create:
  - name: "{{ service }}-{{ env }}"
    resource_type: role

iam_policies_to_attach:
  - policy_name: "{{ deploy_queue_name }}"
    resource_name: "{{ service }}-{{ env }}"
    resource_type: role
